# Generated by Django 4.1.13 on 2024-06-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=None)),
                ('bed_id', models.IntegerField()),
                ('price', models.FloatField(default=None)),
                ('patient_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='distric',
            new_name='district',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_info.status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dob',
            field=models.DateField(),
        ),
    ]
