# Generated by Django 4.1.13 on 2024-06-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0003_alter_rentinfo_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinfo',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
