# Generated by Django 5.0.4 on 2024-04-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='product_details',
        ),
    ]
