# Generated by Django 4.1.13 on 2024-05-31 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.FloatField()),
                ('desc', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('doctor_id', models.IntegerField()),
                ('import_date', models.DateField()),
                ('expiry', models.DateField()),
                ('import_no', models.IntegerField()),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_info.supplier')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_info.type')),
            ],
        ),
    ]
