# Generated by Django 4.1.13 on 2024-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='type',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
