# Generated by Django 4.1.13 on 2024-05-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dianosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.IntegerField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('prescription', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_record_info.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('note', models.CharField(max_length=200)),
                ('dianosis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicine_record_info.dianosis')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_record_info.treatment')),
            ],
        ),
    ]
