# Generated by Django 4.1.13 on 2024-05-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_record_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_record_info.treatment'),
        ),
    ]
