# Generated by Django 4.1.13 on 2024-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_record_info', '0002_remove_treatment_prescription_prescription_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='treatment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='prescriptions',
            field=models.ManyToManyField(to='medicine_record_info.prescription'),
        ),
    ]
