# Generated by Django 4.1.13 on 2024-05-31 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_record_info', '0003_remove_prescription_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medicine_record_info.treatment'),
        ),
    ]
