# Generated by Django 4.1.13 on 2024-05-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bed_numner',
            new_name='bed_number',
        ),
    ]
