# Generated by Django 4.1.13 on 2024-03-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_title', models.CharField(blank=True, max_length=100, null=True)),
                ('searched_author', models.CharField(blank=True, max_length=100, null=True)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookSearch',
        ),
    ]
