# Generated by Django 4.1.13 on 2024-03-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0002_searchlog_delete_booksearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchLog',
        ),
    ]
