# Generated by Django 4.1.13 on 2024-05-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('room', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment_info.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_info.type')),
            ],
        ),
    ]
