# Generated by Django 4.1.13 on 2024-05-31 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
    ]
