# Generated by Django 4.1.13 on 2024-05-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_house', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('hire_date', models.DateField()),
                ('cccd', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_model.address')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_model.department')),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_model.fullname')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_model.role')),
            ],
        ),
    ]
